Repository geertmeersman/mobile_vikings, pull requests merged in 2025-04, with the labels that each got.

#185 feat: JIM Mobile support
  README.md
  custom_components/mobile_vikings/__init__.py
  custom_components/mobile_vikings/binary_sensor.py
  custom_components/mobile_vikings/client.py
  custom_components/mobile_vikings/config_flow.py
  custom_components/mobile_vikings/const.py
  custom_components/mobile_vikings/entity.py
  custom_components/mobile_vikings/models.py
  custom_components/mobile_vikings/sensor.py
  custom_components/mobile_vikings/translations/en.json
  custom_components/mobile_vikings/translations/fr.json
  custom_components/mobile_vikings/translations/nl.json
  images/brand/jimmobile.png
Labels: major, feat

#197 fix: binary sensor data usage alert fixed after JIMMobile merge
  custom_components/mobile_vikings/binary_sensor.py
Labels: patch, fix

#198 docs: JIM Mobile additions
  README.md
  custom_components/mobile_vikings/manifest.json
Labels: patch, docs
